export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_HEADERS = 'FETCH_DATA_HEADERS';
export const FETCH_HEADERS_RELATIVES = 'FETCH_HEADERS_RELATIVES';
export const FETCH_HEADERS_RELATIVES_PHONE = 'FETCH_HEADERS_RELATIVES_PHONE';
export const REMOVE_DATA_PARENT = 'REMOVE_DATA_PARENT';
export const REMOVE_DATA_RELATIVES = 'REMOVE_DATA_RELATIVES';
export const REMOVE_DATA_PHONE = 'REMOVE_DATA_PHONE';